### PR TITLE
Repeating state update

### LINKED ISSUE #1: Don't update state on error after previous success
When retrieving data every X seconds (e.g. getting ERC721 tokens user owns `experimental_tokens`), if a call to API fails, don't update state if the state previously contained data.

### PR DESCRIPTION
**Pull request by ghostbuster91**
This closes #1

### CODE REVIEW

File: src/api.js [hunk 1]
```diff
@@ -167,33 +167,26 @@ export const getMyEntities = async () => {
...
-  try {
-    const identities = await getRanking(
-      [
-        {
-          algorithm: 'cryptoverse_tokens',
-          params: {
-            identity: from.toLowerCase(),
-            asset: ercs721.map(({ address: erc721Address }) => `ethereum:${erc721Address.toLowerCase()}`),
-          },
+export const getEntities = async (from) =>
```
Comment (jakubsta) [inline src/api.js]: Could you check all usages of this function e.g. `getMyEntities` will fail if `getEntities` fails and even address entity will be unavailable.
